### PR TITLE
Moonbeam and Related Ecosystems

### PR DESCRIPTION
**Pull request by themacexpert**
This PR includes significant updates to the Moonbeam ecosystem and adds a number of related ecosystems.

### CODE REVIEW

**Comment by jubos** [comment]
Hi, can you squash your commits into one for easy review?

**Comment by themacexpert** [comment]
Let me know if that did the trick @jubos

**Comment by themacexpert** [comment]
@jubos any changes to make?

**Comment by themacexpert** [comment]
Any revisions I can make? Thank you @jubos

**Comment by jubos** [comment]
Merged this.  I removed a few of the sub ecosystems that weren't Moonbeam specific, but overall looked great!  Thanks again.

**Pull request closed without merging**
