### PR TITLE
Update Moonbeam and Moonriver Ecosystems

### PR DESCRIPTION
**Pull request by themacexpert**
Update Moonbeam, Moonriver, and related ecosystem projects.

### CODE REVIEW

**Comment by jubos** [comment]
Thanks for all of these repos.  We are running them through review and will circle back shortly.  

Initial feedback is that some of the sub ecosystems are EVM native as opposed to Moonbeam specific.  We have a designation for the developer report of primary and secondary ecosystems and looking at exposing it in this repository in a future release.

**Comment by spazcoin** [comment]
orgs/ecosystems that I recognize as unique to the Moonbeam/Moonriver ecosystem are:
* Authtrail
* Beamswap
* Chaotic Finance
* Certhum
* Exiled Racers
* Huckleberry
* Polkadotters
* Ryabina
* Stellaswap     (I included it in #242 also)
* Talisman
* Yield Bay

**Comment by themacexpert** [comment]
> Thanks for all of these repos. We are running them through review and will circle back shortly.
> 
> Initial feedback is that some of the sub ecosystems are EVM native as opposed to Moonbeam specific. We have a designation for the developer report of primary and secondary ecosystems and looking at exposing it in this repository in a future release.

Thanks for taking a look @jubos! Let me know the best way to make any needed adjustments.

**Comment by themacexpert** [comment]
Hey @jubos, let me know how I can help to revise anything, thanks!

**Comment by jubos** [comment]
It would be great to just scope the diff down to the Moonbeam/Moonriver ecosystems and rebase against the master branch. 

I can also help with that.

**Review by jubos — CHANGES_REQUESTED** [review]
This needs a fresh rebase against the master branch.

**Comment by themacexpert** [comment]
Hey @jubos just checking back here, let me know when you get a chance to take a look. Thanks!

**Comment by jubos** [comment]
@themacexpert, it's getting closer.  I still see quite a few ecosystems that aren't primary sub ecosystems to the Moonbeam / Moonriver ecosystems such as SushiSwap, Axelar, Beefy, etc.

Given this is an expansive diff, and it diverges from the master branch, I would suggest breaking it up into some smaller PRs like adding the Authtrail/Beamswap sub ecosystems one at a time, so they can be easily merged.  Then we can do one final PR which adds them as subecosystems to Moonbeam or Moonriver.

**Comment by jubos** [comment]
Thank you for breaking these up.  It was super helpful in getting everything merged.  Want to take another pass at specifying the direct Moonbeam and Moonriver sub ecosystems against the master branch?

**Pull request closed without merging**
