### PR TITLE
Added Core Blockchain

### PR DESCRIPTION
**Pull request by RumeelHussain**
created the `core-blockchain.toml` file for inclusion of **Core Blockchain** into the Electric Capital ecosystem

### CODE REVIEW

**Comment by jubos** [comment]
Thanks, merged this above!

**Comment by RumeelHussain** [comment]
Hi @jubos 
I am unable to get results for **Core Blockchain** on the [Ecosystem Page ](https://www.developerreport.com/)

**Comment by MarryamZulfiqar** [comment]
Hi @jubos @yizhao-ec @mariashen  

Bumping on this. I am unable to get results for Core Blockchain on the [Electric Capital Ecosystem Page](https://www.developerreport.com/)

**Comment by RumeelHussain** [comment]
Hi @jubos @yizhao-ec @mariashen

Bumping on this. Still I am unable to get results for Core Blockchain on the Electric Capital [Ecosystem Page](https://www.developerreport.com/).

**Pull request closed without merging**
