### PR TITLE
Added repositories to solana.toml

### PR DESCRIPTION
**Pull request by notEduardo**

### CODE REVIEW

**Comment by jubos** [comment]
Thanks for monster PR!  We are running these through review and will circle back shortly.

**Comment by 0xnirmal** [comment]
anything I can do to help @jubos? would love to see this get merged in!

**Review by jubos — CHANGES_REQUESTED** [review]
@notEduardo, thanks for this diff, but we can't merge it as is.  There are a lot of duplicates that are already reflected in the sub ecosystems of Solana.  It also casts too wide of a net and pulls in a lot of repos that are not dedicated to Solana like ankr and badger to name a few.

As a next step, if you can scope down the diff into smaller reviewable diffs, it will be much easier to confirm and get them in.  We have also reviewed a bunch of Solana repos internally and will make an update to Solana.toml that should make the job easier.

**Comment by jubos** [comment]
Going to close this out for now.  ff8b5e619faa8258f9e2598593958141f1bf549b added a bunch of new Solana repos + sub ecosystems.  Please rebase against this when you have a moment and reopen the PR with any missing repos.

**Pull request closed without merging**
