### PR TITLE
adding some more projects for Aztec and Noir

### PR DESCRIPTION
**Pull request by signorecello**
Sorry about the second PR, I asked on our channels and some projects came a bit late

### CODE REVIEW

**Review by eherrerosj — APPROVED** [review]
thank you, this looks great

**Review by eherrerosj — CHANGES_REQUESTED** [review]
hey @signorecello, urls look good but validator is failing because of a lot of duplicate repos, can you remove dups plz? https://github.com/electric-capital/crypto-ecosystems/actions/runs/7287878080/job/19859394295?pr=759#step:5:55

Then we can merge

**Comment by signorecello** [comment]
Lazy me asked ChatGPT to check for dups, should’ve run the CI instead

**Comment by signorecello** [comment]
Done now, thanks @eherrerosj

**Comment by jubos** [comment]
Thanks for this.  Manually merged this here [4cf757c](https://github.com/electric-capital/crypto-ecosystems/commit/4cf757c4c951ed8c12ec2db4f728a24c91518711)

**Pull request closed without merging**
