### PR TITLE
Add Kodadot to various L2 subecosystems

### PR DESCRIPTION
**Pull request by yangwao**
We are deploying NFT Explorer on other L2s in Ethereum too

More to verify are here on alpha deployment - https://canary.kodadot.xyz/

### CODE REVIEW

**Comment by eherrerosj** [comment]
A couple fixes needed here @yangwao:
1. Kodadot should be a sub-ecosystem of the supported chains, not the other way around
2. The name used under the `sub_ecosystems` list has to be exactly the same as the ecosystem names in their corresponding toml files, and it is case-sensitive, that's why this is failing

**Comment by yangwao** [comment]
> 1. Kodadot should be a sub-ecosystem of the supported chains, not the other way around

what's the format for that? I should add KodaDot to sub-eco of other chains if I get it right?

> 2\. and it is case-sensitive, that's why this is failing

Ah, I thought after wards I've submitted it, can proceed with fix

**Comment by yangwao** [comment]
Hey @eherrerosj I see green checks now! :)

**Review by eherrerosj — APPROVED** [review]
thanks for the contribution! merging now

**Pull request merged**
