### PR TITLE
celo.toml update

### PR DESCRIPTION
**Pull request by bcamacho**
Updated Celo repos

### CODE REVIEW

**Review by jubos — CHANGES_REQUESTED** [review]
Thank you for these.  A lot of them are GitHub orgs and not repos, so it's not quite ready for being merged.  

Can you either create new sub ecosystems for those or add the specific repos?

A good rule of thumb is if there are other people building in the ecosystem or it has its own Discord and community, it often warrants a new ecosystem being created.

**Comment by jubos** [comment]
Sub ecosystems are automatically pulled up into their parent ecosystem, so it wouldn't affect the metrics negatively.  It just allows for granular categorization of the ecosystems,

**Comment by jubos** [comment]
@bcamacho, can you rebase this against the master branch and fix conflicts.  Then I think it's ready to merge.

**Comment by bcamacho** [comment]
@jubos Updated the fork/branch with upstream for rebase with no issues. We should be good to go for the merge :)

**Pull request merged**
