### PR TITLE
Adding Scroll Ecosystem's sub ecosystems to repo

### PR DESCRIPTION
**Pull request by RandulaKoralage**
A list of missing sub-ecosystems was added to scroll.toml

### CODE REVIEW

**Review by pseudotheos — COMMENTED** [review]
Thanks for contributing!

**Comment by jubos** [comment]
Thanks for these changes.  Can you rebase against the latest master branch, so it merges cleanly?

**Comment by RandulaKoralage** [comment]
@jubos I did a rebase but I feel like I messed up it. Let me know if the PR is not okay to merge.

**Comment by jubos** [comment]
@RandulaKoralage, it's a bit too large of a PR to easily review because there are lot of intermediate commits that are doing merges and adding / removing changes.  What I suggest doing is abandoning this PR and make changes against the latest master branch and break it up into a few PRs that are more easily reviewed and merged. 

For instance, adding a particular ecosystem like Serey as a single PR is really straightforward to review.

**Pull request closed without merging**
