### PR TITLE
update: archi github repo / solana.toml

### PR DESCRIPTION
**Pull request by 0xSense**
updated the solana.toml with github repo.

Author: Sense (0xSense)

### CODE REVIEW

**Comment by eherrerosj** [comment]
nice addition, could you solve the conflict first os I can merge @0xSense ?

**Review by eherrerosj — CHANGES_REQUESTED** [review]
conflicts found

**Comment by 0xSense** [comment]
> nice addition, could you solve the conflict first os I can merge @0xSense ?

Yes I can, fixing the conflict now.

**Comment by 0xSense** [comment]
I believe the conflict was from there being no new line created at the end of the document, I add a new line and committed the change.

**Comment by eherrerosj** [comment]
> I believe the conflict was from there being no new line created at the end of the document, I add a new line and committed the change.

I think it is because we merged other Solana changes, I still see a conflict here
image

**Comment by 0xSense** [comment]
Archi-REpo-ADD

New Commit and all checks have passed and currently says no conflicts now, please let me know if you need me to update anything! 

-Happy Holidays

**Review by eherrerosj — APPROVED** [review]
perfect thank you!

**Pull request merged**
