### PR TITLE
Add Liquid Network

### PR DESCRIPTION
**Pull request by philippem**

### CODE REVIEW

**Comment by jubos** [comment]
This is a great start.  Can you pull out Fuji, Tdex, tokenocean, and liquidnft each into their own sub ecosystem?

**Comment by philippem** [comment]
> This is a great start. Can you pull out Fuji, Tdex, tokenocean, and liquidnft each into their own sub ecosystem?

- what are the criteria for repositories being a sub ecosystem?
- if a repository is part of a sub ecosystem, should it be listed in both places?

thank you

**Comment by philippem** [comment]
> This is a great start. Can you pull out Fuji, Tdex, tokenocean, and liquidnft each into their own sub ecosystem?

Done. I have amended the commit with these changes.

**Comment by jubos** [comment]
Thanks for the updates.  Merged this!

**Pull request merged**
