### PR TITLE
Added solactivity-anchor

### PR DESCRIPTION
**Pull request by zarex5**

### CODE REVIEW

**Review by eherrerosj — APPROVED** [review]
thx!

**Review by eherrerosj — CHANGES_REQUESTED** [review]
hey @zarex5 can you solve the conflict and then I can merge?

**Comment by zarex5** [comment]
> hey @zarex5 can you solve the conflict and then I can merge?

Sure, should be good now

**Comment by jubos** [comment]
Manually merged here: [9996d70](https://github.com/electric-capital/crypto-ecosystems/commit/9996d702963974edba98298f962bff8e2d0469e9)

**Pull request closed without merging**
