### PR TITLE
Adding Greymass contributions to the EOS ecosystem

### PR DESCRIPTION
**Pull request by aaroncox**
We've been meaning to contribute to your awesome reporting mechanisms for a while now, and finally got the nudge by other actors in the EOS ecosystem to contribute some of our projects here. 

Listed in this PR is repositories from both the @greymass and @wharfkit organizations, both which our team develops for.

We have included all of our projects that are either:

- Products (Wallets, Applications, Services)
- Developer Tools (SDKs, Utilities, etc)

There's a lot to add, which represents multiple years worth of work, so apologies in advance for doing this in bulk. 

Please let me know if you have any questions.

### CODE REVIEW

**Review by eherrerosj — APPROVED** [review]
Fantastic additions, thank you! Merging now

**Comment by eherrerosj** [comment]
Could you solve the conflicts first @aaroncox? 🙏🏻

**Review by eherrerosj — CHANGES_REQUESTED** [review]
conflicts

**Comment by aaroncox** [comment]
Thanks for the heads up - no more conflicts! 👍

**Review by eherrerosj — APPROVED** [review]
LGTM now! Will merge. Thanks for the contribution

**Pull request merged**
