### PR TITLE
Create arctic-dex.toml

### PR DESCRIPTION
**Pull request by ArcticDEX**
arctic-dex.toml

### CODE REVIEW

**Review by eherrerosj — CHANGES_REQUESTED** [review]
You forgot quotes in eco names. Also, "Artic DEX" should be in the list of sub_ecosystems of the compatible chains. id, you'll need to modify the ethereum, starknet, zksync erc, aurora, etc tomls

**Comment by ArcticDEX** [comment]
Thank you, i fixed  quotes in eco names and I also  include it in the
proper sub_ecosystems.

Merry X-Mas :)

**Comment by ArcticDEX** [comment]
On sub_ecosystem push i receive some errors: *build*
<https://github.com/electric-capital/crypto-ecosystems/actions/runs/7312347390/job/19922812569>
The following actions uses node12 which is deprecated and will be forced to
run on node16: ***@***.*** For more info:
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Can you please help me? Thank You.

**Review by eherrerosj — CHANGES_REQUESTED** [review]
quotes still missing

**Review by jubos — CHANGES_REQUESTED** [review]
See Enrique's comments above

**Comment by jubos** [comment]
I am closing this one out for now.  Please address the comments and reopen when it's ready.

**Pull request closed without merging**
