### PR TITLE
Update astar-network.toml

### PR DESCRIPTION
**Pull request by TtomaS7**
I've updated a list of the Ecosystem projects, thank you!

### CODE REVIEW

**Comment by TtomaS7** [comment]
May you help me why is it "Invalid subecosystem" error ?

**Comment by platonicsocrates** [comment]
> May you help me why is it "Invalid subecosystem" error ?

Hey Toma! Great question! I believe that since those are sub-ecosystems you need to add the toml files for those projects? Like this one: https://github.com/electric-capital/crypto-ecosystems/blob/09b4f63680bfdc7e1f69ef705dcb07e11d73cccc/data/ecosystems/a/artzero.toml#L6

**Comment by TtomaS7** [comment]
Added 2 repos to check if I got it right

Should I add it for each ecosystem team? 
and should I remove the list of the Ecosystem teams?

**Review by TtomaS7 — COMMENTED** [review]
Updated!

**Comment by platonicsocrates** [comment]
Awesome! Looks like the checks are all passing now! 🎉

**Comment by TtomaS7** [comment]
thank you!!

**Comment by platonicsocrates** [comment]
Anytime!

**Review by eherrerosj — CHANGES_REQUESTED** [review]
hey, thanks for opening a PR.

There's no need to add the repos from the sub-ecosystems that already have those repos, can you please remove the additions of repos that belong to the sub-ecosystems that you added? You can check the toml files of those sub-ecos and see that those already contain the respective repos

**Comment by TtomaS7** [comment]
@eherrerosj  just to clarify if I got your point!
So if the project had already toml file, like AZero for example - https://github.com/electric-capital/crypto-ecosystems/blob/09b4f63680bfdc7e1f69ef705dcb07e11d73cccc/data/ecosystems/a/artzero.toml , I have to remove all the cases as AZero. Is it correct?

**Review by TtomaS7 — COMMENTED** [review]
The doc is updated.

**Comment by TtomaS7** [comment]
hey @eherrerosj 
does it look okay now?
Thank you!

**Review by eherrerosj — APPROVED** [review]
LGTM now, merging. Thanks for the contribution!

**Pull request merged**
