### PR TITLE
Update TON repositories

### PR DESCRIPTION
**Pull request by tsivarev**
Add missed organizations and repositories for The Open Network (TON)

### CODE REVIEW

**Comment by tsivarev** [comment]
Do I need to parse each organization to get repository links?

**Comment by ProgramCrafter** [comment]
https://github.com/ProgramCrafter/ton-qr-deployer

**Comment by tsivarev** [comment]
> https://github.com/ProgramCrafter/ton-qr-deployer

Thank you! Added

**Comment by tsivarev** [comment]
> * https://github.com/Gusarich/multisig-dapp
> * https://github.com/puppycats/multisig
> * https://github.com/puppycats/ton-random

Thank you! Added

**Comment by 0xknstntn** [comment]
https://github.com/0xknstntn/onda-ton

**Comment by tsivarev** [comment]
> Thank you! Added

Thank you! Added

**Comment by tsivarev** [comment]
> https://github.com/0xknstntn/onda-ton

Thank you! Added

**Comment by chakzefir** [comment]
@tsivarev you've added organisation but not repos, could you please add:
https://github.com/Tonstarter/ton-domains-frontend
https://github.com/Tonstarter/ton-domains-backend

**Comment by jubos** [comment]
Thank you, merged these.

**Pull request merged**
