### PR TITLE
WIP: update iota.toml

### PR DESCRIPTION
**Pull request by fhb191309**
Work in progress: Updating information about Iota/Shimmer Ecosystem

ToDo:

- [ ] Add all Subecosystems
- [ ] Add all Github Organizations
- [ ] Add all Repositories

### CODE REVIEW

**Comment by jubos** [comment]
Thanks for the PR.  You will need to add those individual sub ecosystem toml files so that the build will succeed.

**Comment by fhb191309** [comment]
> Thanks for the PR. You will need to add those individual sub ecosystem toml files so that the build will succeed.

Thanks for the heads up. Will be adding those files in the coming updates

**Comment by jubos** [comment]
Going to close this out for now.  Please reopen when you fix the conflicts.

**Comment by fhb191309** [comment]
Sry will start working on resolving the conflicts again, didn't get your notification

**Pull request closed without merging**
