### PR TITLE
add dec15 solana repos

### PR DESCRIPTION
**Pull request by jacobcreech**

### CODE REVIEW

**Review by eherrerosj — APPROVED** [review]
LGTM, thanks @jacobcreech

**Comment by Pham-ngoc** [comment]
https://github.com/Pham-ngoc/ScreamZ

**Comment by NamChuaTeTiengCuoi** [comment]
https://github.com/NamChuaTeTiengCuoi/Solana-Education.git

**Comment by PDLOC** [comment]
https://github.com/PDLOC/OBOOKS

**Comment by vothaidubi2** [comment]
https://github.com/vothaidubi2/Omni-Swap

**Comment by luan0506** [comment]
https://github.com/thanhfire1/ERRO_TEAM

**Comment by machvanquan** [comment]
https://github.com/machvanquan/NFTick.git

**Comment by suytinh546** [comment]
https://github.com/ThuyTuyen11/DuAnXuong---Tranh-NFT

**Comment by Tzinh513** [comment]
https://github.com/HiuBeBa/webBanVeNFT

**Comment by siphuc123** [comment]
https://github.com/siphuc123/NFT_Music_Platforms

**Comment by TriNguyen432** [comment]
https://github.com/TriNguyen432/The-Crazy-Programmers

**Comment by phuphan301** [comment]
https://github.com/phuphan301/golem-pay-later

**Comment by phihoanglongtam** [comment]
https://github.com/DatMin22/NFT-Ticket.git

**Pull request merged**
