### PR TITLE
Create issuaa.toml

### PR DESCRIPTION
**Pull request by avocadodefi**
Create issuaa.toml

### CODE REVIEW

**Review by eherrerosj — CHANGES_REQUESTED** [review]
Hey, a few comments:
1. the link under github organization is a User URL not an Org URL
2. some of the Repo URLs are not properly formatted. The expected format is like https://github.com/org/repo
3. Is ISSUAA an organization / ecosystem? If so, with what chains is it compatible? Please add ISSUAA as sub-ecosystems of those compatible ecosystems

**Review by avocadodefi — COMMENTED** [review]
# Ecosystem Level Information
title = "ISSUAA"

# Assuming ISSUAA is compatible with certain chains, list them in sub_ecosystems.
# Example: sub_ecosystems = ["Ethereum", "Binance Smart Chain"]
sub_ecosystems = []

# Corrected GitHub organization URL
github_organizations = ["https://github.com/issuaa"]

# Repositories - Modified to point to the root of each repository
# Assuming 'issuaa-contracts' is the repository name
[[repo]]
url = "https://github.com/issuaa/issuaa-contracts"

**Comment by avocadodefi** [comment]
Is ISSUAA an organization / ecosystem? If so, with what chains is it compatible? Please add ISSUAA as sub-ecosystems of those compatible ecosystems

Scroll, Berachain, zkSync, ETH

**Review by avocadodefi — COMMENTED** [review]
# Sub Ecosystems
# These are the titles of other ecosystems your site is compatible with or uses
sub_ecosystems = ["Ethereum", "Scroll", "zkSync", "Polygon", "Berachain"]

**Comment by eherrerosj** [comment]
> # Sub Ecosystems
> # These are the titles of other ecosystems your site is compatible with or uses
> sub_ecosystems = ["Ethereum", "Scroll", "zkSync", "Polygon", "Berachain"]

could you modify the toml file of those ecosystems such that it includes "ISSUAA" in the list of sub-ecosystems?

**Review by eherrerosj — CHANGES_REQUESTED** [review]
can you please add "ISSUAA" and "ZK ZAPPER" to the list of sub_ecosystems that they are compatible with? Please do it in this same PR

**Comment by avocadodefi** [comment]
all updated. Thank you for your great support & help.

**Comment by avocadodefi** [comment]
done

**Review by eherrerosj — CHANGES_REQUESTED** [review]
hey @avocadodefi, almost there. The issue is that ArcticDEX, CrossWeave-Protocol and Mantle0x are ecosystems that don't exist in the taxonomy currently (they don't have a toml file), could you add those missing tomls using this same PR (don't open new PRs please) with their corresponding github links?

**Comment by avocadodefi** [comment]
Toml files created for ArcticDEX,  CrossWeave-Protocol and Mantle0x .

**Comment by avocadodefi** [comment]
path was wrong. It has been corrected.

**Pull request merged**
