### PR TITLE
Adding Cosmos/Umee

### PR DESCRIPTION
**Pull request by robert-zaremba**
Redoing the following PR, which was not merged (apparently some error was there)

### CODE REVIEW

**Comment by jubos** [comment]
Sorry about that.  I remerged this with Umee as a Cosmos sub ecosystem.  Peggo will be automatically picked up in Cosmos since Umee is a sub ecosystem, so it doesn't need to be added to the Cosmos eco directly.

**Comment by robert-zaremba** [comment]
Again something was wrong, the PR was not merged. The Umee repo is not listed in `main` branch. So how it can be automatically picked? Should we add Umee to https://github.com/electric-capital/crypto-ecosystems/blob/master/data/ecosystems/c/cosmos.toml#L107  ? Other cosmos chains are listed as independent repos (eg stargaze, osmosis, etc...)

Also, Peggo is a different repository.

**Comment by robert-zaremba** [comment]
I also noticed that the same problem applies to few other cosmos chain (eg: Regen Network)

**Comment by robert-zaremba** [comment]
up, the PR was not merged, instead it was closed.

**Comment by jubos** [comment]
I manually cherry picked the actual changes (74ff43aca5cbb1275926d844009b0f406d97424a) on to avoid dealing with merge branches.  Umee and Regen Network are subecosystems of Cosmos. 

Please let me know if you see any other changes to Cosmos that you want.

**Comment by robert-zaremba** [comment]
How does this resolve the umee repository, which is `https://github.com/umee-network/umee/`? Also we have few other repos: peggo (gravity bridge relayer), ojo (new chain).

**Pull request closed without merging**
