### PR TITLE
Updated celo.toml with the latest project

### PR DESCRIPTION
**Pull request by reachjason**
Added the latest Celo projects to the toml file.

### CODE REVIEW

**Review by jubos — CHANGES_REQUESTED** [review]
This is great, can you rebase against master and sort alphabetically so can deal with the merge in a clean way?

**Comment by jubos** [comment]
@reachjason, any chance you can run your script against master and merge your repos in?

**Comment by reachjason** [comment]
this contains all the repos alphabetically sorted:
https://docs.google.com/spreadsheets/d/1120QwV2KLxcovvVa_BppZaSaOf8I-H0WBZsdV8s4-do/edit?usp=sharing

**Comment by reachjason** [comment]
this commit contains the rebase against master and the entries alphabetized:
https://github.com/electric-capital/crypto-ecosystems/pull/145/commits/c9b6269f4f57809003284a88a3ed72821f46ee69

**Comment by jubos** [comment]
Thanks for fixing this up.  Merged into master!

**Pull request closed without merging**
