### PR TITLE
Additions to internet-computer.toml

### PR DESCRIPTION
**Pull request by tokuryoo**
I added to internet-computer.toml for November.

### CODE REVIEW

**Review by eherrerosj — APPROVED** [review]
thx! Nice contribution. I think we merged another ICP PR recently, could you solve the conflicts first so I can merge @tokuryoo ?

**Comment by tokuryoo** [comment]
@eherrerosj 
I accidentally deleted it from the repository. So I added it to internet-computer.toml.

**Review by eherrerosj — APPROVED** [review]
great additions, ty! merging

**Comment by eherrerosj** [comment]
@tokuryoo Could you solve the conflict please? We will soon refresh the repository and it will avoid you lot more conflicts if we can merge before we refresch

**Comment by jubos** [comment]
Manually merged this with [824b2d1](https://github.com/electric-capital/crypto-ecosystems/commit/824b2d11fcec4fba9221546393e98caa354c861c)

**Pull request closed without merging**
