### PR TITLE
Updated subsquid mentions

### PR DESCRIPTION
**Pull request by RaekwonIII**
I am Subsquid's Developer Advocate and represent them. I have updated our file, to contain most up-to-date information, and took the liberty of adding information about Subsquid to Polkadot and Kusama files as well.

### CODE REVIEW

**Comment by spazcoin** [comment]
Why not simply add `"Subsquid"` in the `Polkadot.toml` file also, instead of adding each individual repo?  (honestly I only discovered this repo last night, so could be wrong)

**Comment by jubos** [comment]
Thanks @RaekwonIII and @spazcoin.  In general, a good rule of thumb is if a project has its own discord / twitter, it is likely its own ecosystem.  

I think Subsquid as sub eco of Polkadot here makes the most sense and to have the repos directly in the Polkadot.toml, but rather in the subsquid.toml.  I will make the changes and get this merged.

**Comment by jubos** [comment]
Merged this.

**Comment by RaekwonIII** [comment]
Hey @jubos , thanks for chiming in and for merging the PR, but your statement and explanation is in contrast with what you ended up doing.
Subsquid **does** have its own Discord and **does** have its own Twitter.
By the rule of thumbs you brought up it should have its own page and repo links should stay in it's toml file.

Did I misunderstand something?

**Comment by jubos** [comment]
Yep, I made the small the change to not have the subsquid repos in the polkadot.toml and just have them in the subsquid.toml.

**Pull request closed without merging**
