### PR TITLE
Adding more repos

### PR DESCRIPTION
**Pull request by muttoni**
Adding more repos, especially those that integrate with FCL.js, the Flow Client Library (i.e. any app building on Flow)

### CODE REVIEW

**Review by jubos — CHANGES_REQUESTED** [review]
Thanks for this update.  Can you remove the DappStarter templates? These are mostly just boilerplate repos.

**Comment by muttoni** [comment]
Done!

**Comment by jubos** [comment]
Thanks for removing those.  I think this PR still needs a bit of filtering.  Are you running an automated process to suggest these repos?  For instance a few are more general and not specific to flow:

https://github.com/RobEnoch/Tatum-js
https://github.com/magiclabs/magic-js
https://github.com/David405/algorand-lending-protocol

In general for tooling that supports multiple ecosystems, those are better suggestions for the General ecosystem. 

Can you do another pass?

**Comment by muttoni** [comment]
Hey @jubos, are we good to merge this now?

**Comment by jubos** [comment]
Thanks merged this!

**Pull request merged**
