### PR TITLE
Fix zkSync name and add more repos

### PR DESCRIPTION
**Pull request by lgingerich**

### CODE REVIEW

**Review by eherrerosj — APPROVED** [review]
great contribution, thank you!

**Comment by rocky4426** [comment]
Great

**Comment by ksmawrdna** [comment]
gg

**Comment by dbarlen** [comment]
wow,...
big project

**Comment by byMAPco** [comment]
Thanks for all.Im proud to be with you!

**Comment by vxhmmo** [comment]
thank

**Comment by Manik417** [comment]
> _ No description provided. _

**Comment by PHunters** [comment]
great

**Comment by 0xboykaa** [comment]
great contribution, thank you for your effort

**Comment by Burakowsky** [comment]
thanks for the contrıbutıon buddy

**Comment by thekera404** [comment]
Great

**Comment by yas3i3** [comment]
ZK

**Pull request merged**
