### PR TITLE
Create kommunitas.toml

### PR DESCRIPTION
**Pull request by kommunitas**

### CODE REVIEW

**Review by eherrerosj — CHANGES_REQUESTED** [review]
please add, in this PR, "Kommunitas" to the list of sub_ecosystems of the compatible blockchains (each has its own toml that you'll need to modify)

**Comment by kommunitas** [comment]
@eherrerosj done

**Comment by jubos** [comment]
@kommunitas, you shouldn't add Kommunitas as a sub ecosystem for itself as that will create a loop.  @eherrerosj was suggesting adding it to Polygon as your website would suggest.

**Comment by kommunitas** [comment]
@jubos @eherrerosj 
I have fixed it, please check

**Review by eherrerosj — APPROVED** [review]
looks good now, thanks @kommunitas

**Pull request merged**
