### PR TITLE
Update sub-ecosystems and add new repos for Base

### PR DESCRIPTION
**Pull request by wbnns**
This PR updates the previous metadata for Base, adding new sub-ecosystems and repos.

### CODE REVIEW

**Review by jubos — CHANGES_REQUESTED** [review]
This is a good start.  I would suggest breaking it up into a few PRs.  First start with adding the existing sub ecosystems to Base.  Then add these new sub ecosystem tomls for the brand new ecosystems that don't exist, so it passes the validation.

**Review by jubos — CHANGES_REQUESTED** [review]
This is getting closer.  I would suggest removing the non-existent ecosystems and sort of the repos for the first pass, and then we can add new ecosystems in separate PRs.

**Comment by wbnns** [comment]
@jubos 

Heya Curtis! Thanks for the feedback! This should all be resolved and ready for merging. 👍

**Comment by jubos** [comment]
Thank you for the updates!

**Pull request merged**
