### PR TITLE
Update aptos.toml

### PR DESCRIPTION
**Pull request by anukulKun**

### CODE REVIEW

**Comment by Celebi07** [comment]
https://github.com/Celebi07/NFTBidX/blob/main/backend/Move.toml

**Comment by Vanshika-Malik2004** [comment]
https://github.com/Dis1309/spheron/blob/main/backend/contracts/Move.toml

**Comment by Him7n** [comment]
https://github.com/Him7n/Meta-Edu-Aptos/blob/main/Blockchain/contract/Move.toml

**Comment by jubos** [comment]
Repo is already added, so I am closing this out.

**Pull request closed without merging**
