### PR TITLE
Update TON repos

### PR DESCRIPTION
**Pull request by tsivarev**
Updated the list of TON repositories

### CODE REVIEW

**Comment by Gusarich** [comment]
Can you please also add:
 * https://github.com/Gusarich/crc32-opcode-helper

**Comment by mr-tron** [comment]
https://github.com/TelegramMessenger/telemint/

**Comment by tsivarev** [comment]
> guys add please https://github.com/yungwine/TonTools https://github.com/yungwine/pytoniq

Thx! Already here :)

**Comment by yungwine** [comment]
Hey, @tsivarev! Looks like there is an old link for the project - https://github.com/yungwine/tonpylib

The library has been renamed and now link is https://github.com/yungwine/pytoniq. 

I'm not sure how important that is, because by default github redirects to the new one, but i think we can change it anyway to avoid confusion 😊

**Comment by tsivarev** [comment]
> Hey, @tsivarev! Looks like there is an old link for the project - https://github.com/yungwine/tonpylib
> 
> The library has been renamed and now link is https://github.com/yungwine/pytoniq.
> 
> I'm not sure how important that is, because by default github redirects to the new one, but i think we can change it anyway to avoid confusion 😊

fixed

**Review by eherrerosj — APPROVED** [review]
Nice work everyone here, merging now. Thanks for the contribution!

**Pull request merged**
