### PR TITLE
Bonzo Finance to Hedera Ecosystem

### PR DESCRIPTION
**Pull request by bmgentile**
Added Bonzo Finance

### CODE REVIEW

**Comment by bmgentile** [comment]
Hi Electric Capital team — i'm receiving an error in the checks above; what can I do to remediate this?

Thanks so much!

**Comment by jblewnormal** [comment]
@bmgentile Hey man, I ran into this issue too. You need to re-order your newlines alphabetically. Viewing the Details of the failed build check will show you there is a single line to change.

**Comment by bmgentile** [comment]
> @bmgentile Hey man, I ran into this issue too. You need to re-order your newlines alphabetically. Viewing the Details of the failed build check will show you there is a single line to change.

Ah! Thank you so much.

**Review by yizhao-ec — APPROVED** [review]

**Comment by bmgentile** [comment]
Hmm still having issues here:
1. Added Bonzo Finance file as its own "ecosystem" under /b/
2. Included this ecosystem as a "subecosystem" for hedera.toml

It's throwing this error: `Invalid subecosystem for Hedera -> Bonzo Finance`

**Pull request merged**
