### PR TITLE
Add Starknet sub-ecosystems and repos

### PR DESCRIPTION
**Pull request by boyuanx**

### CODE REVIEW

**Comment by boyuanx** [comment]
@jubos Not sure why it keeps throwing an error ;(

**Comment by mariashen** [comment]
@boyuanx ah it's because "Nova" and "Permit3" don't have valid .toml files

**Comment by boyuanx** [comment]
@mariashen Thank you, I misunderstood the structure of everything. Fixed :)

**Comment by jubos** [comment]
Thank you for this.  I fixed up the remaining merge conflicts and merged here: ef595c238063d8596d6838e2be9f031fae7a1239

**Pull request closed without merging**
