### PR TITLE
Apex Ecosystem Creation with Cairo

### PR DESCRIPTION
**Pull request by SriCrypt**
This is an example ecosystem I tried to create with Cairo

### CODE REVIEW

**Comment by script-money** [comment]
It's not Starknet cairo code

**Comment by SriCrypt** [comment]
> It's not Starknet cairo code

I uploaded the wrong code. not it is fixed.

**Comment by script-money** [comment]
> > It's not Starknet cairo code
> 
> I uploaded the wrong code. not it is fixed.

hello world code?

**Comment by SriCrypt** [comment]
> > > It's not Starknet cairo code
> > 
> > 
> > I uploaded the wrong code. not it is fixed.
> 
> hello world code?
we can contribute anything using cairo language. it does not  matter whether is it simple or big code

**Comment by eherrerosj** [comment]
closing for now as I don't see how Starknet is being used here

**Pull request closed without merging**
