### PR TITLE
Update eos.toml

### PR DESCRIPTION
**Pull request by Lilbansheemebe**
Adding repos from Pomelo Grant Process seasons 1-6 to the EOS ecosystem

### CODE REVIEW

**Review by eherrerosj — CHANGES_REQUESTED** [review]
Hi @Lilbansheemebe, some feedback so you can iterate through with changes before we merge:
1. Some repo links are really not repo link but org links and they should be under the `github_organizations` list
2. For the links referred to in 1), some of them are links of github user accounts and not really github organization accounts, example: https://github.com/boid-com
3. Some repo links are missing and can be removed, example: https://github.com/Bywire-News-Official/bywire.web

**Comment by Lilbansheemebe** [comment]
@eherrerosj Thank you for the feedback! I'll fix those.

**Comment by Lilbansheemebe** [comment]
@eherrerosj apologies for the delay, I have reviewed the repo links and removed any that were not legit repo links (I hope I got them all)

**Comment by jubos** [comment]
@Lilbansheemebe, I am going to close this out.  Can you please reopen and rebase against the latest master branch to address @eherrerosj's comments if you want to revisit this?

**Pull request closed without merging**
