### PR TITLE
Elrond update

### PR DESCRIPTION
**Pull request by schimih**
November update for Elrond Ecosystem.

NOTE:
-next month we will start the migration to MultiversX;

### CODE REVIEW

**Comment by schimih** [comment]
Done,
Thanks!

**Comment by schimih** [comment]
Hey Jubos,
I've updated the branch, Thanks again!

**Comment by jubos** [comment]
@schimih, any chance you can add just the commits that have changes to the latest master branch, so it merges cleanly?

**Comment by schimih** [comment]
Created a new PR:
https://github.com/electric-capital/crypto-ecosystems/pull/337

**Pull request closed without merging**
